### ISSUE TITLE
acosh with alpha=0?

### ISSUE THREAD

**Issue by shashwatsahay** [const-ae/transformGamPoi-Paper#6]
Hey,

Very nice paper firstly.

I was going through the [benchmark results notebook](https://htmlpreview.github.io/?https://github.com/const-ae/transformGamPoi-Paper/blob/master/notebooks/plot_benchmark_results.html) and I noticed for the $`acosh(2\alpha y/s+1)`$ transformation the alpha goes to 0 but isn't that mathematically equivalent $`acosh(1)`$, as alpha of zero basically would neutralise $`y/s`$. Or am I missing something here

**Comment by const-ae** [comment]
Hi Shashwat,

thanks :)

Well spotted. You are right that $\lim_{\alpha \rightarrow 0}\text{acosh}(2\alpha y/s+1) = 0$. But importantly, with the appropriate scaling factor $\lim_{\alpha \rightarrow 0}  \frac{1}{\sqrt{\alpha}}  \text{acosh}(2\alpha y/s+1) = 2 \sqrt{y/s}$. You can check this with [WolframAlpha](https://www.wolframalpha.com/input?i=lim+x+-%3E+0+%5B1%2Fsqrt%28x%29+acosh%282+*+x+*+y+%2Fs+%2B+1%29%5D). The square-root transformation is the variance stabilizing transformation of the Poisson distribution and a Gamma-Poisson distribution with an overdispersion of $\alpha = 0$ reduces to the Poisson distribution. In that sense, the variance-stabilizing transformation is consistent.

In `transformGamPoi::acosh_transform`, I distinguish `alpha = 0` and either call `.acosh_trans_impl ` or `. sqrt_trans_impl` (https://github.com/const-ae/transformGamPoi/blob/devel/R/delta_method_transform.R#L100)

**Comment by shashwatsahay** [comment]
This took me some time and reading up to understand m y math concepts are down the drain..

And I forgot that there was a scalling factor involved in the main section of the paper where the formula 1 is defined. 🤦‍♂️ 

Thanks, I understand now. Also could you  let me know if I am correct within the scope of the paper the acosh transformation was tested with 0 and 0.05 is there a reason for that

**Comment by const-ae** [comment]
> the acosh transformation was tested with 0 and 0.05 
> is there a reason for that

I chose zero because it corresponds to a Poisson-noise assumption. This is popular in the field, but has been debated and I found it interesting to see how the other methods compare. The `0.05` is somewhat arbitrary. Based on the Suppl. Tab. S1, I have a rough idea what the overdispersion is in data which includes biological variation. Accordingly, I chose a small non-zero value. This is in line with the thresholds discussed in [Lause's (2021) paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-021-02451-7).
